### ISSUE TITLE
Curl version bottle neck

### ISSUE THREAD

**Issue by thatdoorsajar** [spatie/laravel-uptime-monitor#104]
Not an issue with the package as such, but the requirement of curl version higher than 7.49.1 seems to be a bit of a bottle neck to usage in the Laravel community unless I am missing something.

My very recent install of Homestead and my very recently forge spun server are both at `curl -V // 7.47.0` 

It seems to be quite hard to update curl on a server. Any pointers to get curl 7.49.1 or higher installed?

**Comment by sebastiandedeyne** [comment]
What package is that curl requirement coming from?

**Comment by thatdoorsajar** [comment]
It's listed on the spatie/laravel-uptime-monitor V2 requirements docs here: https://docs.spatie.be/laravel-uptime-monitor/v2/requirements

**Comment by sebastiandedeyne** [comment]
Hmm not sure how important that is since it's not enforced in the `composer.json` (it should if it's really necessary). Gonna have to wait for @freekmurze to tell us why that version's necessary!

**Comment by thatdoorsajar** [comment]
OK, since the package is none function breaking I will give it a test on my server @ curl 7.47.0 in the meantime.

Thanks for the quick reply!

**Comment by thatdoorsajar** [comment]
It seems that everything is working on both Homestead and a Forge provisioned DO server which are both using curl @ 7.47.0 - tested passing scheduled monitors and monitors I set to fail.

I can close the issue but maybe there is a discrepancy in the package documentation?

**Comment by freekmurze** [comment]
curl 7.49.1 is the version on my Mac, so that where that requirement probably came from.

However curl 7.47 is fine to run the package. We use that version on our own server that does the uptime checks for us.

I've updated the docs page.

**Comment by thatdoorsajar** [comment]
Thanks @freekmurze 

Another brilliant package you guys have created. I can now go on holiday for 2 weeks and theres another problem I don't have to keep worrying about!
