### ISSUE TITLE
User Domain Input should not be modified

### ISSUE THREAD

**Issue by mallardduck** [spatie/laravel-uptime-monitor#107]
If a user inputs:

`https://example.com/somepage/`

The tool should not remove the trailing slash, a user might have a good and necessary reason to include the trailing slash. For example, if the Canonical URL includes the trailing slash then the user should be including it as well.

Currently the tool will remove the trailing slash which is causing an issue for me. I understand the idea of removing it; as it helps normalize URLs and reduce duplicate entries, but maybe that could be done without modifying the users input?

**Comment by freekmurze** [comment]
Implementing this feature would bring complexity to the package that's not needed for most users.

The easiest way for you to overcome to problem is to create a page on your site that works with the url that this package is using to check uptime.

**Comment by stijnh92** [comment]
Hi @freekmurze, can I ask you why this would bring complexity? Why does this happen in the first place?
Having an issue with this at the moment...
