### ISSUE TITLE
Domain expiration check

### ISSUE THREAD

**Issue by Rhincodon** [spatie/laravel-uptime-monitor#108]
Would be great if uptime monitor can check domain expiration date

**Comment by freekmurze** [comment]
Domain expiration data isn't available in a common structured way for all domains. So chances are that feature will never make it in the package.

If you do find an easy way of retrieving domain expiration dates for all domains, let me know (or send a PR).

**Comment by vesper8** [comment]
https://github.com/io-developer/php-whois is an actively developed php solution that does an excellent job of returning whois data on just about every TLD out there. There may be a handful that don't work but I think it would be worth just catching those exceptions and offering the ability which would be useful in 99% of cases

what do you think @sixlive ?
