### ISSUE TITLE
duplicated 'in' in certification expires mail

### ISSUE THREAD

**Issue by larsbo** [spatie/laravel-uptime-monitor#112]
Hi, I'm not sure if this is related only to the german output of `diffForHumans` but there are two `in`s behind each other in the notification mails:
![bildschirmfoto 2017-09-04 um 08 53 44](https://user-images.githubusercontent.com/754074/30014897-caa2c068-914e-11e7-8b7f-e44ac866ffff.png)

**Comment by michdess** [comment]
This issue does not occur if using English. I checked by modifying locale in Carbon to German (Carbon::setLocale('de');) and it does indeed still happen in German - not sure if other languages are similarly affected. 

![screen shot 2018-02-21 at 10 33 54 pm](https://user-images.githubusercontent.com/22342988/36472684-665d10ce-1757-11e8-981b-23fbbb3254e6.png)

![screen shot 2018-02-21 at 10 39 34 pm](https://user-images.githubusercontent.com/22342988/36472978-260bc8de-1758-11e8-9e1e-03531df29547.png)

This isn't a fix (not sure what the best course of action to resolve would be) but hopefully this clarifies the issue.

**Comment by SamuelNitsche** [comment]
Unfortunately, carbon is not very consistent in translation.
The easiest way to fix this is to use Laravel's built-in translation feature.

**Comment by freekmurze** [comment]
Seems like this will need to be addressed in Carbon first.
