### ISSUE TITLE
SSL error when website is not using default port 443

### ISSUE THREAD

**Issue by M0ter** [spatie/laravel-uptime-monitor#115]
When adding a up-time check for websites with non default port the SSL check is still done on default 443 instead of the port specified in the up-time entry.

example

artisan monitor:create https://sub.domain.com:8843

SSL Certificate for https://sub.domain.com:8843 is invalid
Could not download certificate for host `sub.domain.com` because stream_socket_client(): unable to connect to ssl://sub.domain.com:443 (Connection refused)

**Comment by freekmurze** [comment]
I'd accept a PR that fixes this problem.

**Comment by AlexBys** [comment]
Hi, the fix i was able to come up with requires changes to the ssl-certificate package.

**Comment by sebastiandedeyne** [comment]
Feel free to open a PR to our ssl-certificate package if necessary :)

https://github.com/spatie/ssl-certificate
