### ISSUE TITLE
Feature Request: Multiple Strings monitored on a single url

### ISSUE THREAD

**Issue by benyanke** [spatie/laravel-uptime-monitor#116]
One useful feature would be the ability to run multiple-string checks on a single URL.

This could be accomplished most simply by not using the URL as the key in the database, and allowing multiple checks on a URL.

**Comment by sebastiandedeyne** [comment]
How about allowing regex strings, wouldn't that be a simpler solution?

**Comment by freekmurze** [comment]
You could write your own `UptimeResponseChecker` for this, which could look for multiple strings.
