### ISSUE TITLE
Feature Request: Custom Headers on an individual monitor

### ISSUE THREAD

**Issue by benyanke** [spatie/laravel-uptime-monitor#118]
Custom headers per-monitor would make this much more scalable and flexible, allowing things like checks behind HTTP digest auth.

(By the way, with all these feature requests, I'm hoping to help implement some of them myself, I'm just putting them here for tracking purposes, in case anyone else wants to as well).

**Comment by sebastiandedeyne** [comment]
We'd accept a PR that adds this in a non-breaking way.

**Comment by sixlive** [comment]
@benyanke the ability to add custom headers was added with https://github.com/spatie/laravel-uptime-monitor/pull/127 and released with [3.1.0](https://github.com/spatie/laravel-uptime-monitor/releases/tag/3.1.0)

**Comment by benyanke** [comment]
Beat me to it!
