### ISSUE TITLE
Feature Request: Checks behind HTTP Auth

### ISSUE THREAD

**Issue by benyanke** [spatie/laravel-uptime-monitor#119]
Allow specifying creds in the database on a per-check basis, then pass those to check the site behind the login.

**Comment by sebastiandedeyne** [comment]
I think that's be beyond the scope of this package. If the login page returns a 200 response, the site can be considered up, since it's most likely running on the same server as whatever's behind it.

This would add a but too much complexity for an edge case.

**Comment by sebastiandedeyne** [comment]
Also, I think #118 is a better issue for this, you could always ensure basic auth is available :)
