### ISSUE TITLE
Feature Request: Port/Services Check

### ISSUE THREAD

**Issue by benyanke** [spatie/laravel-uptime-monitor#120]
Not sure how possible this is, but one potential monitoring feature could be checking for services/ports. This would allow monitoring if a given service crashed and stopped listening on a port, for example, the ssh daemon or a fileserver.

Not sure how this would be best accomplished. Perhaps with a telnet wrapper? Or something like this: https://github.com/jnorell/Net_Telnet

**Comment by sebastiandedeyne** [comment]
This sounds more like something our server monitor can take care of, I'd prefer to keep this one simple :)

https://github.com/spatie/laravel-server-monitor

**Comment by benyanke** [comment]
Fair enough!
