### ISSUE TITLE
Question - Not yet checked - does not get processes

### ISSUE THREAD

**Issue by thim81** [spatie/laravel-uptime-monitor#126]
We love the uptime package and we use to monitor +200 site.

But for some reasons, the list of `Not yet checked` does not get processed?
Is it because the 'concurrent_checks' ? Are they too high or too low?

Currently we have it configured > 'concurrent_checks' => 500

Any tips would be helpful.

**Comment by freekmurze** [comment]
What do you mean with ` not get processed`? Try lowering the concurrent checks to a sane value like 5 and start the checking process.

**Comment by thim81** [comment]
Hi Freek,

When using the list command there are 2 lists:
- not yet processed list
- the list with all ✅

We will try lowering the concurrent setting to see if it reduces the "not yet processed list"

Thanks for your Quick response and the powerfull package. 

Regards,
Tim

**Comment by freekmurze** [comment]
Reopen if this is still an issue.
