### ISSUE TITLE
Unable to edit url

### ISSUE THREAD

**Issue by thunder87** [spatie/laravel-uptime-monitor#134]
**Spatie\UptimeMonitor\Models\Monitor**

```
public function getUrlAttribute()
{
    if (! isset($this->attributes['url'])) {
        return;
    }

    return Url::fromString($this->attributes['url']);
}
```

How would you show and edit the url attribute?
- because I'm getting an `[object Object]` on the url (JS).

Trying to extend the model and overwrite this behaviour
- but I'm unable to extend my App\Monitor with: `Spatie\UptimeMonitor\Models\Monitor`

**Comment by freekmurze** [comment]
You can get the value stored in the db with:

```php
$monitor->attributes['url']
```

You can update the value as usual:

```php
$monitor->url = 'example.com';
$monitor->save();
```

Our tests indicate that all behaviour around using your own model is working properly. Did you set the right model in the config file of the package?

https://docs.spatie.be/laravel-uptime-monitor/v3/advanced-usage/using-your-own-model
