### ISSUE TITLE
Fails to check certificate without the php-intl extension

### ISSUE THREAD

**Issue by viirre** [spatie/laravel-uptime-monitor#137]
When running the certificate checks (`php artisan monitor:check-certificate`), I get this error:

`Symfony\Component\Debug\Exception\FatalThrowableError  : Call to undefined function Spatie\SslCertificate\idn_to_ascii()`

This is because on my mac (running Valet) I don't have the `php-intl` extension loaded. After installing it (by running `brew install php71-intl`) everything works as expected.

Shouldn't this be noted in the docs (in the `Requirements` section) since (from my understanding), that extension is not installed by default on most machines?

Thanks for an excellent package :)

**Comment by viirre** [comment]
So when checking some more, I see that the `php-intl` extension is required by the `spatie/ssl-certificate` (which the uptime requires), but not until in a very recent version (this needs `^1.5.0` but should need `>=1.12.4`).

So bumping the version needed for the `spatie/ssl-certificate` will throw an error message when requiring this package if I don't have the extension installed. 

Do think that it should be noted in the docs though.

**Comment by freekmurze** [comment]
In normal circumstances composer will not allow you to even install the ssl-certificate package without php-intl being installed.

I'll add a note to the readme that the extension is required.
