### ISSUE TITLE
Prevent duplicate notifications

### ISSUE THREAD

**Issue by chalda-pnuzig** [spatie/laravel-uptime-monitor#138]
Hi, 
When a site go down for 1 hour I get 12 notifications (1 every 5 minutes).
Can I prevent multiple notifications for the same error?
Or better, can I set how often a reminder will be sent? 
Thanks,

**Comment by freekmurze** [comment]
The package can throttle such notifications: https://github.com/spatie/laravel-uptime-monitor/blob/master/config/uptime-monitor.php#L27-L31

**Comment by chalda-pnuzig** [comment]
Mmh... I set resend_uptime_check_failed_notification_every_minutes to 60 but I continue to receive a notification every 1 minute

**Comment by freekmurze** [comment]
Try running `php artisan cache:clear`
