### ISSUE TITLE
Sending and verifying a payload

### ISSUE THREAD

**Issue by mpenna** [spatie/laravel-uptime-monitor#139]
This is just a request for some clarification, please. 

The documentation on the "Sending and verifying a payload" topic mentions that one of the database fields that will need some manual updating is the "uptime_check_get_method". I have checked and rechecked the monitors table and there's no such field. There is, instead, a "uptime_check_method" field. 

Is this a documentation typo or does this mean that this field must be added to the table so to allow for payload verification?

tks

**Comment by freekmurze** [comment]
It's a typo. `uptime_check_method` is the correct name. I've fixed the docs.
