### ISSUE TITLE
Custom Event Handler

### ISSUE THREAD

**Issue by rehmatworks** [spatie/laravel-uptime-monitor#145]
Can we use a custom event handler? Or is there a way to use the `User` class as notifiable? The purpose is to allow multiple users use the same installation but set their own email and other notification channels associated to their account. Currently I feel that we can only use the hardcoded settings for email and slack. Any help will be highly appreciated.

**Comment by freekmurze** [comment]
You can override the notifiable to be used: https://github.com/spatie/laravel-uptime-monitor/blob/eb546d028352b25dcb7f74e082f57d414b9e680d/config/uptime-monitor.php#L45
