### ISSUE TITLE
URL null

### ISSUE THREAD

**Issue by DominikGeimer** [spatie/laravel-uptime-monitor#147]
Hi,

I try to use laravel uptime monitor but the url is alway null. See attached Screenshot from my Tinker.

![spatie monitor](https://user-images.githubusercontent.com/6383607/44535494-64530f80-a6fa-11e8-887d-c350b8002b25.png)

Any idea?

**Comment by DominikGeimer** [comment]
Bump

**Comment by freekmurze** [comment]
The tests of this package seem to indicate that the package is working as intended. Please follow the installation instructions. If you still have troubles using it, please ask questions on a public forum such as the Laracasts forum, laravel.io or StackOverflow.
