### ISSUE TITLE
SSL check fails if an invalid domain is detected.

### ISSUE THREAD

**Issue by rehmatworks** [spatie/laravel-uptime-monitor#148]
If SSL check is enabled for a non-SSL domain, then an exception is thrown and SSL check fails for all other domains as well.

```php
/home/vagrant/uptimemonitor/app/Exceptions/Handler.php(39): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Spatie\\SslCertificate\\Exceptions\\InvalidUrl))
```

For example if there are two domains, one with valid SSL (i.e. https://google.com) and other an invalid domain (hxxp://nonexistenthost.tld), then SSL check will fail for the valid domain as well.

**Comment by freekmurze** [comment]
Fixed in latest version.
