### ISSUE TITLE
Fopen Error

### ISSUE THREAD

**Issue by satrox28** [spatie/laravel-uptime-monitor#151]
Hi,

Whenever the site is down or any error, receiving below error in slack notifications.

https://abcd.com seems down  
Error creating resource: [message] fopen(https://abcd.com): failed to open stream: Connection timed out
[file] /uptime-monitor-app/laravel/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 323  

Can you help me fix this issue

**Comment by freekmurze** [comment]
Seems like this is intended behaviour, the notification tells you want went wrong.
