### ISSUE TITLE
Manually Created Monitors strip URL Scheme

### ISSUE THREAD

**Issue by robbfountain** [spatie/laravel-uptime-monitor#164]
I'm attempting to manually add a monitor using a model that extends Spatie\UptimeMonitor\Models\Monitor but every time I try to add the url, something is stripping the scheme.

attempting to enter `https://example.com` will result in example.com in the database.  The scheme is stripped every time.  

Any ideas why?

This code below will create a monitor successfully but with the url of `example.com`
```php
 Monitor::create([
                'url'                              => 'https://example.com',
                'zone_id'                          => $zone->id,
                'uptime_check_method'              => 'head',
              'certificate_check_enabled'        => $zone->getScheme() === 'https',
               'uptime_check_interval_in_minutes' => config('uptime_monitor.uptime_check.run_interval_in_minutes'),
            ]);
```

**Comment by sixlive** [comment]
Hey! I just tested this out and it seems to be working correctly?

<img width="1265" alt="screen shot 2019-03-08 at 1 54 29 pm" src="https://user-images.githubusercontent.com/5108034/54049152-c3193b80-41a9-11e9-977e-4814553db043.png">

**Comment by sixlive** [comment]
Closing since I can't re-create and no response for OP. If this is an issue feel free to re-open.
