### ISSUE TITLE
Change Default String Length in Migration For 

### ISSUE THREAD

**Issue by zack-carlson** [spatie/laravel-uptime-monitor#165]
For anyone who has set Schema::defaultStringLength(191), then posthumously updated to MySQL 5.7, the uptime monitor fails to update / notify as a SQL error is triggered when the response contains HTML output: `SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'uptime_check_failure_reason' at row 1`

Changing the datatype of uptime_check_failure_reason to TEXT alleviates the issue and causes the monitor work as expected.

**Comment by freekmurze** [comment]
Thanks for posting this! 👍
