### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by freekmurze** [spatie/laravel-uptime-monitor#166]
I don't have the time to maintain this package anymore.

I'm looking for someone that can handle issues, PRs and Laravel upgrades for this package. Preferably that someone has already some experience with open source.

If this is you: let me know!

**Comment by simoebenhida** [comment]
Yeah i could help with that 👍

**Comment by sixlive** [comment]
I could be up for it

**Comment by wotta** [comment]
Is there also an option that someone with less experience could help out with someone who has done it before?

If that is the case i would like to help out with someone who has more experience.

**Comment by freekmurze** [comment]
The job goes to @sixlive because I already know him personally and I know he's up to this 👍 Thanks TJ!

Thank you @wotta @simoebenhida for your offer to help.
