### ISSUE TITLE
Laravel 5.8 Support

### ISSUE THREAD

**Issue by eldiddio** [spatie/laravel-uptime-monitor#168]
Can this package be updated to support Laravel 5.8?

Thanks

**Comment by freekmurze** [comment]
@sixlive is on the case.

**Comment by sixlive** [comment]
Yup. I’ll have it ready today or tomorrow.

**Comment by sixlive** [comment]
Just have some Scrutinizer things to tighten up and we'll be good to go. Track #167.

**Comment by sixlive** [comment]
Tagged [3.4.0](https://github.com/spatie/laravel-uptime-monitor/releases/tag/3.4.0)
