### ISSUE TITLE
Do not follow redirects

### ISSUE THREAD

**Issue by noahfrederick** [spatie/laravel-uptime-monitor#170]
I would like to assert a 301 or 302 HTTP status code in an uptime check. This is not currently possible, because the Guzzle client will follow any redirects and report the final destination's status code.

I propose [configuring the Guzzle client](http://docs.guzzlephp.org/en/stable/quickstart.html#redirects) to never follow redirects. I cannot think of any scenario where following a redirect in a checker would be desirable. This would be a breaking change.

If this is not acceptable, I propose instead that the package allows for passing in an `$options` array to the Guzzle factory: https://github.com/spatie/laravel-uptime-monitor/blob/6d572374a315bf3098ff38fa2dcc331886a8697f/src/MonitorCollection.php#L43

**Comment by sixlive** [comment]
I'm thinking that adding a global config or Guzzle setting would be appropriate, would that work for you in this case?

**Comment by noahfrederick** [comment]
> I'm thinking that adding a global config for Guzzle setting would be appropriate, would that work for you in this case?

Yes, I think that would work nicely. So [this call](https://github.com/spatie/laravel-uptime-monitor/blob/6d572374a315bf3098ff38fa2dcc331886a8697f/src/MonitorCollection.php#L42-L45) would become something like:

```php
        $client = GuzzleFactory::make(
            config('uptime-monitor.guzzle_options', []),
            config('uptime-monitor.uptime-check.retry_connection_after_milliseconds', 100)
        );
```

**Comment by sixlive** [comment]
Yeah, something like that! I'd be willing to accept a PR with tests.

**Comment by atymic** [comment]
PR open in #181

**Comment by atymic** [comment]
@freekmurze this can be closed now BTW :)

**Comment by freekmurze** [comment]
Thanks!
