### ISSUE TITLE
Should CURL error be pushed to slack?

### ISSUE THREAD

**Issue by albertStaalburger** [spatie/laravel-uptime-monitor#172]
I started testing the package a bit and found that the curl error message gets logged in the DB, but isn't being sent to the notification channel, if it has been set to slack.
Is there a config setting that should be set for this?

I am using Laravel and Linux server, all other notifications seem to be working...

**Comment by albertStaalburger** [comment]
Could not reach <my app url> error: `cURL error 28: Connection timed out after 10026 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`
As mentioned, the mail gets sent, but this error or message isn't being received in slack.

**Comment by sixlive** [comment]
Are you still receiving a failed check notification when this curl error happens or is this failure completely silent?

**Comment by albertStaalburger** [comment]
I am receiving a failed check notification in the terminal, but slack still doesn't notify.
The DB status also gets updated to `down` with the relevant curl error message as well as the updated timestamp.

**Comment by sixlive** [comment]
Ahh, ok. I feel like you should get a notification in this instance. I'd be willing to accept a PR or I can look further at it this weekend.

**Comment by sixlive** [comment]
Can you decern if the curl error is happening during the monitor check or is the curl error happening when trying to hit the slack webhook?

**Comment by albertStaalburger** [comment]
I have done some more testing, it appears that `cURL error 7` is coming through, `cURL error 28` wasn't working. After redeploying and re-entering the Slack key `cURL error 28` is also being logged now.

I will add breakpoints to the `monitor check` as well as the `webhook` section and see if anything irregular happens. If so I will reopen the issue.
Thank you for the help.

**Comment by connecteev** [comment]
@albertStaalburger I am seeing the exact same issue. 
```
cURL error 7: Failed to connect to mydomain.com port 443: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
```
and sometimes I dont get notified on my notification channels (Slack or email). Did it end up working for you?

**Comment by pir8g33k** [comment]
Hi guys im having issue i setup the server and its working fine except for email notification and slack notification doesnt work at all, anyone has solution on this? how can we test that the webhook url is wokring?
