### ISSUE TITLE
How to json_encode the eloquent reponse

### ISSUE THREAD

**Issue by dabonzo** [spatie/laravel-uptime-monitor#173]
I want the database data in json format. 
It's not really possible because the url-field is always an object. I tried it in several ways to get only the url-string but no luck.
```php

// Models/Monitor.php

  public function getUrlAttribute()
    {
        if (! isset($this->attributes['url'])) {
            return;
        }

     return Url::fromString($this->attributes['url']);
    }
```

This is the piece of code that always converts the url-string in an URL-object. 
Is there some way to override it when needed, like for a correct json-response.

**Comment by sixlive** [comment]
Can you give me a use case? I'm willing to work on this and I'd like to make sure we are solving the problem with the correct solution.

**Comment by dabonzo** [comment]
Use case:
Providing correct JSON that can be consumed by e.g. Datatables (js) via ajax.

I have a dirty workaround (caution -  beginner)
```` php
// in the extended Monitor model I had to hide the url field
protected $hidden = ['url'];

// before JSON output I had to iterate over the collection and add a new field which name can't be url
// I had to use the __toString method explicitly. Without it, I again got the URL-object

        $monitor_json = $monitors->map( function($value){
            $value['json_url'] = $value->url->__toString();
            return $value;
        });

// There's probably a better way. I'm still not there though

```

**Comment by dabonzo** [comment]
After reading through the older issues I found this solution.
https://github.com/spatie/laravel-uptime-monitor/issues/86

**Comment by sixlive** [comment]
Yeah, I think that makes a lot of sense.

**Comment by sixlive** [comment]
Does #175 look like it will work for you?

**Comment by dabonzo** [comment]
Yes, thank's a lot !!!

**Comment by sixlive** [comment]
Awesome, I'll merge and tag later today

**Comment by sixlive** [comment]
Tagged in https://github.com/spatie/laravel-uptime-monitor/releases/tag/3.5.0
