### ISSUE TITLE
certificate_check_failure reason truncated

### ISSUE THREAD

**Issue by dabonzo** [spatie/laravel-uptime-monitor#176]
```
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'certificate_check_failure_reason' at row 1
```
We had a problem with uptime_check_failure_reason also. Maybe change the datatype to text also.

https://github.com/spatie/laravel-uptime-monitor/issues/165

**Comment by sixlive** [comment]
I'll consider changing it to `TEXT`. In the meantime, you could publish the migration and make the update yourself.

**Comment by atymic** [comment]
@sixlive 
Happy to open a PR and add tests if required :)

**Comment by sixlive** [comment]
@atymic that would be great!

**Comment by D-sense** [comment]
@atymic, please has this issue been fixed? Because I am having the same problem as mentioned above. Can I open a PR and add a test if required?

**Comment by atymic** [comment]
I haven't yet.
You can create the PR 😄

**Comment by D-sense** [comment]
> I haven't yet.
> You can create the PR 😄

@atymic 
PR has been created a few hours ago. Thank you 😄
