### ISSUE TITLE
Get SSL status for IP address.

### ISSUE THREAD

**Issue by rehmatworks** [spatie/laravel-uptime-monitor#177]
Some IP addresses are served over a valid SSL but the SSL check with the uptime monitor fails. For example 1.1.1.1 is CloufFlare's IP address for DNS and that serves a valid SSL.

**Comment by sixlive** [comment]
I'm going to look into this further. I'm a bit short on time today but I'll get to it this week. If you want to open a PR in the meantime I'd be happy to review!

**Comment by dabonzo** [comment]
I had a problem with some domains getting a valid ssl check. In a browser, it would work but the check would fail. It was a server problem. A browser can autodiscover intermediate certificates, in the console the intermediate certificate has to be provided through the web server configuration. In my case, that intermediate certificate was missing.
https://one.one.one.one (1.1.1.1's A record) returns a valid SSL for me though

**Comment by sixlive** [comment]
This makes sense as my test worked fine. I’m going to chalk this up to a server issue and close. Thanks @dabonzo!

If you feel I closed this without solving your problem I’m willing to continue the discussion.
