### ISSUE TITLE
Cannot use database driver

### ISSUE THREAD

**Issue by rehmatworks** [spatie/laravel-uptime-monitor#178]
When trying to use database driver in an extended notification class, the following error is raised:

```php
Call to undefined method Spatie\UptimeMonitor\Notifications\Notifiable::morphMany()
```

**Comment by sixlive** [comment]
Can you post more of the extended notification class so I can get more context?

**Comment by rehmatworks** [comment]
@sixlive Thanks for checking in. BTW I sorted out the issue by using user model as the notifiable rather than using the default notifiable. For information, here is my extended class:

```php
<?php

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Spatie\UptimeMonitor\Notifications\Notifications\UptimeCheckFailed as SpatieUptimeCheckFailed;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Spatie\UptimeMonitor\Events\UptimeCheckFailed as MonitorFailedEvent;

class UptimeCheckFailed extends SpatieUptimeCheckFailed
{
    use Queueable;

    public function via($notifiable)
    {
        return ['mail', 'database'];
    }

    public function setEvent(MonitorFailedEvent $event)
    {
        $this->event = $event;
        return $this;
    }

    public function toArray($notifiable)
    {
        return [
            'message' => $this->getMessageText()
        ];
    }

}
```

**Comment by sixlive** [comment]
Using a user model is the appropriate solution. After all inheritance, it ultimately ends up extending [Illuminate\Notifications\Notification::class](https://github.com/illuminate/notifications/blob/master/Notification.php) and never actually has a connection to the database. You would need to use a notifiable that is attached to a model.

I'm still familiarizing myself to the intricacies of this package but this is how I understand it at the moment. I'm going to go ahead and close this as I feel you made the correct adjustment and this isn't an issue with the package itself.
