### ISSUE TITLE
SSL problem reports site offline (but is up!)

### ISSUE THREAD

**Issue by goyne** [spatie/laravel-uptime-monitor#179]
I'm not sure if this is how it should be. I'm testing around with the package and one of my sites is reported offline (which is certainly not the case!).

The reason given by the package (see screen dump):

> cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

<img width="1117" alt="Schermafbeelding 2019-05-20 om 21 21 41" src="https://user-images.githubusercontent.com/2893526/58047538-b5d4e180-7b48-11e9-8420-443cd33ac00a.png">

Ok, the certificate needs a little work (I guess), but it seems to me that this is no reason to report the site down? Even Google believes the certificate is valid.

<img width="480" alt="Schermafbeelding 2019-05-20 om 21 49 10" src="https://user-images.githubusercontent.com/2893526/58047852-78bd1f00-7b49-11e9-86a8-4f774a6e5c38.png">

Have used the default configuration (as shipped with the package, latest version) on a clean Laravel installation (also the latest version).

Any clue on this? I'm pulling my hair out since the site is very very up...

**Comment by sixlive** [comment]
Hmm I’ll take a closer look, this is a CURL error so I’ll have to look at the Guzzle configuration.

**Comment by dabonzo** [comment]
It's a problem with the webserver configuration. You are probably missing the intermediate certificate. It doesn't matter if there isn't one for browsers (they can autodiscover them() but at the console (to perform the check) the complete certificate chain has to be provided. Check if you have the 
SSLCertificateChainFile set

**Comment by dabonzo** [comment]
About the error the site is down, this is by design. If the certificate check fails, the package considers the site is down
Check https://github.com/spatie/laravel-uptime-monitor/issues/90

**Comment by goyne** [comment]
Thanks for the info @dabonzo 
If the reported downtime is by design, I think that should be reconsidered. In my opinion there's a difference between an offline site and an online site with an unhealthy certificate. Marking the site as down is then too heavy...

**Comment by sixlive** [comment]
I agree with @dabonzo that this is a server error. I feel like this might be a false positive if it is a server issue but if there was legitimately an issue with the certificate your site would be unreachable and therefore "down" to any users or other services.

**Comment by goyne** [comment]
I completely don't understand this.

- Most important of all: the very site is up. Reachable for any user.
- The package is promised to be able to monitor uptime (again: the site is up) _AND_ **certificate health**.

Reporting the site down and ignoring the certificate health (which is the case) doesn't make sense at all. As you can see in my first screen dump, the package ignores certificate checks.

My expectations:
- The site is reported up (since it is reachable)
- The certificate is reported unhealthy (there's no certificate report given).

I agree, there are problems with the certificate. Yet I think the package does not handle the check results properly.

**Comment by sixlive** [comment]
Lets get some clarity, maybe we aren't on the same page.

**The site is reported up (since it is reachable)**
>Most important of all: the very site is up. Reachable for any user.

In the browser, its up but it's not according to the monitor. If it can't negotiate SSL then it is effectively unreachable.

**The certificate is reported unhealthy (there's no certificate report given)**
>The package is promised to be able to monitor uptime (again: the site is up) AND certificate health.

Are you running certificate checks as well as uptime checks? Is the uptime failing due to the cert but the cert check is passing? (this would absolutely be a problem)

**Comment by goyne** [comment]
Thanks @sixlive for the explanation. We were indeed not on the same page. The difference between monitor check and browser is now clear to me.

About your second question, yes, the monitor for this site is configured to check both uptime and certificate health. Maybe the certificate check cannot be performed because the site is unreachable for the monitor?

**Comment by sixlive** [comment]
>Maybe the certificate check cannot be performed because the site is unreachable for the monitor?

This is correct.
