### ISSUE TITLE
Bug: Status Code wrong

### ISSUE THREAD

**Issue by adam-devapp** [spatie/laravel-uptime-monitor#180]
I wrote a custom class to check the status code, but the status code returned to your class is always 200.. The Guzzle code is correct, but doesn't appear to be the same code passed to the interfaces.

class ExampleChecker implements UptimeResponseChecker
{
    public function isValidResponse(ResponseInterface $response, Monitor $monitor) : bool
    {
        dd($response->getStatusCode()); // Always returns 200.
    }

Brand new install of Laravel 5.8, and your extension. 

```
    "require": {
        "php": "^7.1.3",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.8.*",
        "laravel/tinker": "^1.0",
        "spatie/laravel-uptime-monitor": "^3.5"
    },
```

**Comment by adam-devapp** [comment]
This error occurs because an exception is thrown.

When I added the http_errors to the filter, it is removed when run, so I change to a merge.

```
    protected function getPromises(): Generator
    {
        $client = GuzzleFactory::make(
            [],
            config('uptime-monitor.uptime-check.retry_connection_after_milliseconds', 100)
        );

        foreach ($this->items as $monitor) {
            ConsoleOutput::info("Checking {$monitor->url}");

            $promise = $client->requestAsync(
                $monitor->uptime_check_method,
                $monitor->url,
                **array_merge**([
                    'connect_timeout' => config('uptime-monitor.uptime_check.timeout_per_site'),
                    'headers' => $this->promiseHeaders($monitor),
                    'body' => $monitor->uptime_check_payload,
                    **'http_errors' => false**
                ])
            );

            yield $promise;
        }
    }

```

The requests are then passed correctly to the check to make the exception decision.

**Comment by atymic** [comment]
I'm pretty sure that's the intended behaviour. Guzzle will only throw exceptions for `4xx` or `5xx` status codes.

As long as your server returns a `2xx` response code the check will pass.

**Comment by sixlive** [comment]
The status code sent to the checker will only be 200-300 level codes, 400 and 500 throw an exception and will fail the checker.

**Comment by atymic** [comment]
> The status code sent to the checker will only be 200-300 level codes

Only 2xx codes until we allow automatic redirect disabling.
