### ISSUE TITLE
check behind login too?

### ISSUE THREAD

**Issue by jayenne** [spatie/laravel-uptime-monitor#186]
Hi all.
does the post/payload allow checking behind laravel login too? I'm wondering if/how it handles the csrf token.

Checking behind the login would be super helpful in checking if the DB is up, or if other pages using thirparty services such as connected to Twitter still returns a stream for example.

I guess, If it doesn't login via Auth then I'll need to write some API to return those tests then.

**Comment by vdbelt** [comment]
No, it doesn't handle CSRF tokens. 

The package is pretty flexible though, so you could write your own monitor / response checker to get what you need.

Easiest would however probably be to do as you suggested, creating a custom endpoint that includes the checks you'll want to monitor.
