### ISSUE TITLE
Can't change Slack notifications 

### ISSUE THREAD

**Issue by sergeypoprovka** [spatie/laravel-uptime-monitor#187]
Hi!

Encountered a problem with changing `per_user` notifications. Everything works fine for email notifications, but not for Slack. If I'm using default notifications - everything is working great! BUT! After changing Notifiable class and Failed and Success notification classes - email still works, but slack is not.

Steps to reproduce:
1. Chang Notifiable class:
```class CustomNotifiable extends Notifiable
{
    public $email;
    public $slack;

    /**
     * @return string|null
     */
    public function routeNotificationForMail()
    {
        return $this->email;
    }

    /**
     * @return string|null
     */
    public function routeNotificationForSlack()
    {
        return $this->slack;
    }
}
```

2. Create and change Notification class itself:
```
class UptimeCheckFailed extends \Spatie\UptimeMonitor\Notifications\Notifications\UptimeCheckFailed
{
    /**
     * Get the mail representation of the notification.
     *
     * @param  mixed  $notifiable
     * @return \Illuminate\Notifications\Messages\MailMessage
     */
    public function toMail($notifiable)
    {
        $notifiable->email = $this->event->monitor->user->email;

        $mailMessage = (new MailMessage)
            ->error()
            ->subject($this->getMessageText())
            ->line($this->getMessageText())
            ->line($this->getLocationDescription());

        foreach ($this->getMonitorProperties() as $name => $value) {
            $mailMessage->line($name.': '.$value);
        }

        return $mailMessage;
    }

    public function toSlack($notifiable)
    {

        $notifiable->slack = $this->event->monitor->user->slack_webhook_url;

        return (new SlackMessage)
            ->error()
            ->attachment(function (SlackAttachment $attachment) {
                $attachment
                    ->title($this->getMessageText())
                    ->content($this->getMonitor()->uptime_check_failure_reason)
                    ->fallback($this->getMessageText())
                    ->footer($this->getLocationDescription())
                    ->timestamp(Carbon::now());
            });
    }
}
```

3. Model `Monitor` extends Spatie's Monitor model:

```
class Monitor extends \Spatie\UptimeMonitor\Models\Monitor
{
    public function user(){
        return $this->belongsTo(User::class);
    }
}

```

4. Config file changed to contain my classes as notification classes, my new model that extends Spatie's model and Notifiable class changed to be CustomNotifiable.

At this point I'm having email notifications working and they're sent to user's email (owner of the monitor), but Slack is not working at all.

What am I doing wrong? Any help appreciated!
Thanks in advance :)

/S

**Comment by atymic** [comment]
Could you try putting a `Log::debug()` call in the slack method to see if it's called?

I assume you added it to the `via()` as well?

```php
     /**
     * Get the notification's delivery channels.
     *
     * @param mixed $notifiable
     * @return array
     */
    public function via($notifiable)
    {
        return ['mail', 'slack'];
    }
```

**Comment by sergeypoprovka** [comment]
@atymic 
Yes, `slack` is listed at `via` method, since it's added to /config/uptime-monitor.php file 
```
'notifications' => [
            \App\Notifications\UptimeCheckFailed::class => ['slack','mail'],
            \Spatie\UptimeMonitor\Notifications\Notifications\UptimeCheckRecovered::class => [],
            \App\Notifications\UptimeCheckSucceeded::class => ['slack'],

            \Spatie\UptimeMonitor\Notifications\Notifications\CertificateCheckFailed::class => ['slack'],
            \Spatie\UptimeMonitor\Notifications\Notifications\CertificateExpiresSoon::class => ['slack'],
            \Spatie\UptimeMonitor\Notifications\Notifications\CertificateCheckSucceeded::class => [],
        ],
```

and... No. I've tried to add `dd($notifiable)` to Slack method and it's not hit :(

/S

**Comment by atymic** [comment]
My next suggestion would be use xdebug to figure out exactly why it isn't working. Put a breakpoint [here](https://github.com/spatie/laravel-uptime-monitor/blob/master/src/Notifications/EventHandler.php#L27) and trace where it goes wrong.

**Comment by sergeypoprovka** [comment]
@atymic  Tried it, but TBH or I'm missing smth or the info from XDebug doesn't contain any useful info at this case. Cuz every time I'm receiving instance of notification class at the Xdebug->Debugger view and `$event` with `$monitor` inside it. 
Probably I'm looking at the wrong place :( 

/S
