### ISSUE TITLE
Add support for telegram notifications

### ISSUE THREAD

**Issue by uran1980** [spatie/laravel-uptime-monitor#189]
Add support for telegram notifications.

**Comment by sergeypoprovka** [comment]
@uran1980 
https://github.com/laravel-notification-channels/telegram
Some tweaks to Notifier class and Notifications themselves - and you have Telegram notifications

**Comment by uran1980** [comment]
Thank, already done, but I would like to to have this functionality builde in

**Comment by atymic** [comment]
> Thank, already done, but I would like to to have this functionality build-in

You can submit a PR :)
