### ISSUE TITLE
README links to abandoned project

### ISSUE THREAD

**Issue by TechWilk** [spatie/laravel-uptime-monitor#202]
In the README, there is a link to the uptime-monitor-app, which is now abandoned.

>If you're not familiar with Laravel, but still want to use our uptime monitor, take a look at the [uptime-monitor-app](https://github.com/spatie/uptime-monitor-app) repo which contains a stand alone version of this package.

Possibly replace with a simple quick start instructions for installing within laravel.

**Comment by freekmurze** [comment]
Feel free to PR this.
