### ISSUE TITLE
Prepare for Laravel 8

### ISSUE THREAD

**Issue by rcerljenko** [spatie/laravel-uptime-monitor#205]
Laravel 8 will be released on September 8th. Can we check that the library is safe to work with Laravel 8 and update the composer version flags accordingly?

**Comment by rcerljenko** [comment]
ping

**Comment by gldrenthe89** [comment]
+1 and ping!

**Comment by BrandonDR** [comment]
+1

**Comment by eele94** [comment]
+1 pong

**Comment by henryavila** [comment]
Please, update this. It's blocking upgrading my app.

**Comment by ApexMuse** [comment]
> Please, update this. It's blocking upgrading my app.

Same here.  Spatie has been great about upgrading their other packages; hopefully they'll get to this one soon.

**Comment by freekmurze** [comment]
Support for Laravel 8 has been added. If you even don't want a self hosted solution, take a look at https://ohdear.app 😉
