### ISSUE TITLE
Not getting notification email

### ISSUE THREAD

**Issue by bhattraideb** [spatie/laravel-uptime-monitor#211]
I am not getting site down notification email.

I have updated 2 parameters in the config file:

`'resend_uptime_check_failed_notification_every_minutes' => 5,

        'mail' => [
            'to' => ['myemail@gmail.com'],
        ],`

Is there anything else I need to take care of?

I check cron/command is running without error.

**Comment by tominon** [comment]
Did you change notifications from slack to mail in config as well?

**Comment by bhattraideb** [comment]
Thanks @tominon for the response.

I have updated notifications array and looks like this, But still not working.

`notifications' => [

        'notifications' => [
            \Spatie\UptimeMonitor\Notifications\Notifications\UptimeCheckFailed::class => ['mail'],
            \Spatie\UptimeMonitor\Notifications\Notifications\UptimeCheckRecovered::class => ['mail'],
            \Spatie\UptimeMonitor\Notifications\Notifications\UptimeCheckSucceeded::class => [],

            \Spatie\UptimeMonitor\Notifications\Notifications\CertificateCheckFailed::class => ['mail'],
            \Spatie\UptimeMonitor\Notifications\Notifications\CertificateExpiresSoon::class => ['mail'],
            \Spatie\UptimeMonitor\Notifications\Notifications\CertificateCheckSucceeded::class => [],
        ],

II have created custom views for error messages, will that matter?

Thanks,
Deb

**Comment by tominon** [comment]
Is email sending working in your application? Can you test it via [Mail facade](https://laravel.com/docs/8.x/mail#sending-mail)? What mail driver do you use?

**Comment by bhattraideb** [comment]
Yes, email is working I just check the contact us form from [here](https://rococopelton.com/contact). I am using mailgun.

**Comment by chilly2go** [comment]
I did wonder about something similar. How I approached the problem was by first receiving mails on "CheckSucceeded" events. Once that worked it was clear that my general setup was ok.
After that I found that I wouldn't get a mail about my monitoring target being down on the first fail and that it had to be down for a longer period for the default setup system to send a notification.
You would have to change the `fire_monitor_failed_event_after_consecutive_failures` setting to get a notification sooner.

Could you check if this solves your problem?

**Comment by bhattraideb** [comment]
@chilly2go,
I did not get you. On which file and what should I change?

**Comment by ondamedia** [comment]
the `uptime-monitor.php` config file holds the settings. you have already shown the area about notifications.

For `UptimeCheckSucceeded` you currently don't send any notification. Please add notification via mail to that event to check if general event notifications via mail works for your system / setup.

if it works the next question would be why you did not get a notification about system downtime.

**Comment by bhattraideb** [comment]
I updated the file like:
`'notifications' => [
            \Spatie\UptimeMonitor\Notifications\Notifications\UptimeCheckFailed::class => ['mail'],
            \Spatie\UptimeMonitor\Notifications\Notifications\UptimeCheckRecovered::class => ['mail'],
            \Spatie\UptimeMonitor\Notifications\Notifications\UptimeCheckSucceeded::class => ['mail'],

            \Spatie\UptimeMonitor\Notifications\Notifications\CertificateCheckFailed::class => ['mail'],
            \Spatie\UptimeMonitor\Notifications\Notifications\CertificateExpiresSoon::class => ['mail'],
            \Spatie\UptimeMonitor\Notifications\Notifications\CertificateCheckSucceeded::class => ['mail'],
        ],`

But it's still not working.
When I run the command manually like php artisan monitor:check-uptime, it shows the following message:

Start checking the uptime of 0 monitors...
All done!

But not getting email.

**Comment by chilly2go** [comment]
you are saying that your system tells you that it has nothing to check and expect mails for monitors it didn't touch?

just add a monitor that gets checked every minute for testing purposes.
