### ISSUE TITLE
PHP version (8.0.3) does not satisfy that requirement

### ISSUE THREAD

**Issue by pefstra** [spatie/laravel-uptime-monitor#218]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - spatie/laravel-uptime-monitor v4.x-dev requires php ^7.4 -> your PHP version (8.0.3) does not satisfy that requirement.
    - graham-campbell/guzzle-factory v4.0.1 requires php ^7.2.5 -> your PHP version (8.0.3) does not satisfy that requirement.
    - graham-campbell/guzzle-factory v4.0.0 requires php ^7.2.5 -> your PHP version (8.0.3) does not satisfy that requirement.
    - Conclusion: don't install spatie/laravel-uptime-monitor 4.0.1
    - Conclusion: remove graham-campbell/guzzle-factory v5.0.0
    - Installation request for spatie/laravel-uptime-monitor ^4.0 -> satisfiable by spatie/laravel-uptime-monitor[4.0.0, 4.0.1, v4.x-dev].
    - Conclusion: don't install graham-campbell/guzzle-factory v5.0.0
    - spatie/laravel-uptime-monitor 4.0.0 requires graham-campbell/guzzle-factory ^4.0 -> satisfiable by graham-campbell/guzzle-factory[4.0.x-dev, 4.1.x-dev, 4.2.x-dev, v4.0.0, v4.0.1, v4.0.2, v4.0.3, v4.1.0, v4.2.0].
    - Can only install one of: graham-campbell/guzzle-factory[4.0.x-dev, v5.0.0].
    - Can only install one of: graham-campbell/guzzle-factory[4.1.x-dev, v5.0.0].
    - Can only install one of: graham-campbell/guzzle-factory[4.2.x-dev, v5.0.0].
    - Can only install one of: graham-campbell/guzzle-factory[v4.0.2, v5.0.0].
    - Can only install one of: graham-campbell/guzzle-factory[v4.0.3, v5.0.0].
    - Can only install one of: graham-campbell/guzzle-factory[v4.1.0, v5.0.0].
    - Can only install one of: graham-campbell/guzzle-factory[v4.2.0, v5.0.0].
    - Installation request for graham-campbell/guzzle-factory (locked at v5.0.0) -> satisfiable by graham-campbell/guzzle-factory[v5.0.0].

**Comment by J-T-McC** [comment]
Looks like you might be trying to use the 4.0 branch. If you run `composer require spatie/laravel-uptime-monitor` you will get the tagged 4.0 version that supports php 8.

**Comment by pefstra** [comment]
This is what I run and get the above error.

**Comment by J-T-McC** [comment]
It definitely works for php 8 (I am currently using it and you can see the tests passing under actions for 8.0.3). Perhaps try removing it from your package.json, delete your vendor and try a fresh require.

**Comment by pefstra** [comment]
Finally I made it by adding manually to the composer.json "spatie/laravel-uptime-monitor": "4.0"

**Comment by J-T-McC** [comment]
I recommend changing it to “^4.0” so you can get updates.

**Comment by pefstra** [comment]
1. If I change to “^4.0” it tries to install spatie/laravel-uptime-monitor v4.x-dev and I get the error about requirements.

2. When I try the command monitor:check-uptime manualy via ssh everything is fine. But when I schedule it I get this error in log: 
syntax error, unexpected 'Command' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'Command' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) at /home/vendor/spatie/laravel-uptime-monitor/src/Helpers/ConsoleOutput.php:9)
