### ISSUE TITLE
Error Migrating DB

### ISSUE THREAD

**Issue by aaemnnosttv** [spatie/laravel-uptime-monitor#22]
I'm trying to get started with the package and having a bit of trouble.

Env:
- fresh Laravel 5.3.15
- spatie/laravel-uptime-monitor 0.0.3
- added service provider in `config/app.php`
- using sqlite db
- ran `php artisan vendor:publish --provider="Spatie\UptimeMonitor\UptimeMonitorServiceProvider"`

When migrating the DB I get this error:

![image](https://cloud.githubusercontent.com/assets/1621608/19012665/6d23fdfc-87cd-11e6-84ac-478d195536fa.png)

Am I missing something?

Thanks!

**Comment by freekmurze** [comment]
This package is not finished. It's currently in a pre alpha state so there are lots and lots of bugs and  unfinished functionality.

Please be patient for a few weeks while I finished to code.

I've put a little note in the readme to make this clear.
