### ISSUE TITLE
Can't use an SSL URL with a custom port

### ISSUE THREAD

**Issue by adam-devapp** [spatie/laravel-uptime-monitor#221]
When using https:// in a URL, the spatie SSL package will only use 443. This means URLs with custom ports can't have their certificates checked.

**Comment by Benny7587** [comment]
I think I have the same question. I would like to check the certificate on mail.mydomain.com on port 993. Can this be done. I'm using LetsMonitor.org for the mail subdomain now but would be happy to do it with laravel-uptime-monitor.

**Comment by iMateo** [comment]
@adam-devapp, port 443 is tuned in `Spatie\SslCertificate\Downloader::class` but there is a hack 😁

You can use this construction for custom Monitors:
`SslCertificate::download()
   ->usingPort($customPort)
   ->forHost($hostName);`

but for this you definitely need you own Monitor Model here
`'monitor_model' => Spatie\UptimeMonitor\Models\Monitor::class,`
