### ISSUE TITLE
Unable to use with Laravel Zero

### ISSUE THREAD

**Issue by mallardduck** [spatie/laravel-uptime-monitor#222]
Per the title, I found this package isn't compatible with Laravel Zero. This seems to be because the dependency is set to `framework`. See here:
https://github.com/spatie/laravel-uptime-monitor/blob/9aa452e16dbd56d3d6db47b8a42d3d498f7628b5/composer.json#L22

Since it calls for framework instead of the components it uses something like laravel zero breaks. Since composer then struggled to resolve the class as it had copies of them from laravel-zero and laravel proper. However it does seem like this could be easily adjusted to allow support.

I'm just guessing though there may be more to the story behind the choice to tag laravel framework directly. So rather than bothering with a PR first I wanted to open the issue here. I am confident it will work since I've done some local testing to get things working in laravel-zero.

**Comment by PaolaRuby** [comment]
No story behind, it's more simple call `laravel/framework` because it was made for using with oficial laravel framework

**Comment by mallardduck** [comment]
@PaolaRuby - well sure, I follow that much.

I was just seeking context from the spatie guys or maintainers to understand if a PR would be accepted. In theory if it tagged components instead then it will work the same, but support zero. Which even tho it's not "official" it is created by a Laravel core team member so had some legitimacy to it if that's the concern.

**Comment by PaolaRuby** [comment]
The package maintainers don't spend much time around here, just make the PR and expose your need, maybe in a few months they will review it

```
"illuminate/cache": "^8.7",
"illuminate/config": "^8.7",
"illuminate/console": "^8.7",
"illuminate/container": "^8.7",
"illuminate/contracts": "^8.7",
"illuminate/events": "^8.7",
"illuminate/filesystem": "^8.7",
"illuminate/support": "^8.7",
"illuminate/testing": "^8.7"
```

**Comment by mallardduck** [comment]
@PaolaRuby - I've finally had time to come back to this and updated the composer.json requirements. I believe I have all tests working and things seem to pull in via composer as expected for the project I need this change in.

In theory if you have any desire to use this with Lumen you could test the branch and give feedback on the PR. 😄
