### ISSUE TITLE
Using check response

### ISSUE THREAD

**Issue by loranger** [spatie/laravel-uptime-monitor#224]
Hello,

Thank you for this awesome package.
I'd like to fetch and store check responses (code, message and response time) in order to graph monitors uptime, but I can't figure out the best way to do it.
I was thinking I could get the check on each monitor using the uptime events, but it seem I can only have th e monitor itself.

After digging a little, it seems response is only usable as a promise from MonitorCollection.
Is there a place where guzzle instance, or response is exposed in order to be used without messing with the package source code?

**Comment by AbdallaMohammed** [comment]
Is there any solution or work around for this?
