### ISSUE TITLE
Notifications not working

### ISSUE THREAD

**Issue by AshboDev** [spatie/laravel-uptime-monitor#225]
Hi there,

Firstly, great package, loving how easy it is to use.

This could be user error, however I'm having an issue sending notifications via the `mail` channel. It's only this package I'm having these issues with. I'm using `spatie/laravel-welcome-notification` which works without any issues, and I'm able to send one through Tinker with the below:

```
Mail::raw('Hello World!', function($msg) {$msg->to('myemail@gmail.com')->subject('Test Email'); });
```

Both welcome emails and tinker emails hit my postmark, so I'm unsure what might be happening. It's also worth noting I'm using SMTP for postmark, and not the postmark driver. I'm manually running the `php artisan monitor:check-certificate` command, with my config setup like so:

```
'notifications' => [
        \Spatie\UptimeMonitor\Notifications\Notifications\CertificateCheckFailed::class => ['mail'],
        \Spatie\UptimeMonitor\Notifications\Notifications\CertificateExpiresSoon::class => ['mail'],
        \Spatie\UptimeMonitor\Notifications\Notifications\CertificateCheckSucceeded::class => ['mail'],
],
```

So I'm trying to send on the 'check succeeded' class to test it all, manually running the artisan command to make a successful check, to my postmark endpoint, but to no avail.

Would someone mind looking at this with me as a kind of sanity check to ensure I've not missed something probably glaringly obvious?

Again - it's probably user error, so I do apologise in advance!

Thanks in advance,
Ash

**Comment by iMateo** [comment]
@AshboDev, did you clear you config cache?
`php artisan config:cache`
It's common issue with email configuration. Tinker is working without config cache instead of Laravel app.

**Comment by AshboDev** [comment]
> 
> 
> @AshboDev, did you clear you config cache? `php artisan config:cache` It's common issue with email configuration. Tinker is working without config cache instead of Laravel app.

Hi Mateo,

Thank you for the reply, much appreciated! I have done yep, including `php artisan optimize` (Which runs `php artisan config:cache` first) but sadly, no success :(

**Comment by iMateo** [comment]
@AshboDev, did you put your email address to `./config/uptime-monitor.php`
`'mail' => [
            'to' => ['you-mail@domain.tld'],
        ],`

**Comment by AshboDev** [comment]
> 
> 
> @AshboDev, did you put your email address to `./config/uptime-monitor.php` `'mail' => [ 'to' => ['you-mail@domain.tld'], ],`

I have yes, and that same email (in `./config/uptime-monitor.php`) is what I sent a test email to using tinker - which worked. So the destination works using tinker command in my OP, but not using the package. Much sad!

**Comment by iMateo** [comment]
@AshboDev, suggest App uses Queue for email sending, so try to run also `php artisan schedule:work`
Also, I just checked similar configuration, it's works well.

**Comment by AshboDev** [comment]
> 
> 
> @AshboDev, suggest App uses Queue for email sending, so try to run also `php artisan schedule:work` Also, I just checked similar configuration, it's works well.

Wow, I didn't even consider this - it works on dev when I manually run the queue on my laptop, will get it running on the server also and report back with the results. I think this will probably be the answer, and as suspected, user error!

Will report back a little later today!
