### ISSUE TITLE
Domain expiration date check

### ISSUE THREAD

**Issue by adamale** [spatie/laravel-uptime-monitor#322]
Hi there,

have you thought about adding a feature that would also look up a whois response for specified domains and send a notification if a domain is about to expire? This would definitely turn this package into a complex tool for maintaining and monitoring domains.

**Comment by freekmurze** [comment]
If you want domain monitoring, take a look at [Oh Dear's domain monitoring check](https://ohdear.app/docs/general/domain-monitoring).
