### ISSUE TITLE
Question/Help Needed: Install uptime monitor for multi tenant infra

### ISSUE THREAD

**Issue by venkatvghub** [spatie/laravel-uptime-monitor#41]
Hi,

I have a quick question on using the uptime monitor in one of our apps. We have multiple instances (hosted on aws) running our code. We want to be monitoring some internal and external urls using the uptime monitor and trigger events for downtime via a webhook or like to be consumed by an external api. However, the problem arises if the uptime monitor is running on multiple instances leading to duplication. Since our infra is stateless, with autoscaling enabled, we cannot also expect that the uptime should only be run on any single instance at any point of time. Do you guys have any suggestions on running this efficiently? Again, hosting a separate instance for this seems counter intuitive, since i need to run an external monitor to make sure that instance is up and running. Any help would be appreciated.

Thanks.

**Comment by freekmurze** [comment]
We run the uptime monitor on a separate server and that works great for us. Personally I'd never run the uptime check from within an app it is monitoring. 

Do want makes the most sense for your environment.
