### ISSUE TITLE
[Idea] Monitor not only http

### ISSUE THREAD

**Issue by LKDevelopment** [spatie/laravel-uptime-monitor#50]
Hello,

is it planed that this package implement more monitors than only for http? (Such things as Database, Redis, SMTP)?

**Comment by freekmurze** [comment]
There currently are no plans for that.

**Comment by LKDevelopment** [comment]
@freekmurze is that something that i should implement as new package or in the "core"? What do you think?

**Comment by freekmurze** [comment]
If the required changes are simple I'd consider merging it into this package. If not, than it's best to create your own package. Code it up and submit a PR for me to review.

**Comment by LKDevelopment** [comment]
I think changes are only required https://github.com/spatie/laravel-uptime-monitor/blob/master/src/MonitorCollection.php#L26-L47, where it is to check if the Monitor has http(s) or any other protocol (mysql://,redis://,postgres://, smtp://). The Connection to the new protocols could be implemented with Laravel Onboard Functions (as sample for database: https://laravel.com/docs/5.3/database#using-multiple-database-connections ). So it is really simple and useful too.

**Comment by freekmurze** [comment]
Sure the check part itself is not that difficult but to integrate it well there are some things that need to be considered:

- currently the package only checks stuff that is public. In order for db connection checking to work credentials need to be stored, the `monitor:create` needs to be updated to ask for those credentials.
- to ensure the package will work with a lot of monitors, Guzzle promises are leveraged. Connection checking should leverage promises as well to avoid a single slow or non responding db keeping the other checks waiting

Although it's a cool feature, I don't need the db check myself. In all my projects if the database is down, the site will go down as well and the uptime check will send a notification of that. Generally speaking  I only want to maintain stuff I use myself (or code that's very simple). Currently I think that there would be too much changes required for me to merge this into the package. But I hope you prove me wrong 😄

**Comment by LKDevelopment** [comment]
I think, because this is an uptime monitor, it would be really nice to check more than http. And i think that we don't need the credentials in the system because: If we want to connect without credentials and the server is up, it will send something like unauthorized, if the server is down it get an timeout.   And the performance point is, in my opinion, only a thing "how high would be the timeout?" I think an timeout from 1  second is the minimal timeout whe could use.

**Comment by freekmurze** [comment]
You could add a config value for that timeout so the user can choose.

**Comment by LKDevelopment** [comment]
Yeahr, that would be possible too. So what do you think? Should i start coding  😄 ?

**Comment by freekmurze** [comment]
Sure, if you need this, start coding. If it's lightweight enough for me to maintain, I'll pull it in, otherwise you can fork the package and maintain your own copy with the changes. Hurray for opensource.

**Comment by LKDevelopment** [comment]
So i have the first things functional: https://github.com/LKDevelopment/laravel-uptime-monitor/commit/17c3dff42d0c93640013e75b8ee61270e162a79c  Are a little bit more changes, but it allows the users to add own checkers if they need it.
