### ISSUE TITLE
Cachet support?

### ISSUE THREAD

**Issue by m1guelpf** [spatie/laravel-uptime-monitor#51]
Could you add support for a status page api like Cachet. Thank you!

**Comment by LKDevelopment** [comment]
I've planed an new package for this if @freekmurze said that he wouldn't implement it.

**Comment by freekmurze** [comment]
Here's that API package by @LKDevelopment : https://github.com/LKDevelopment/laravel-uptime-monitor-api

**Comment by LKDevelopment** [comment]
Here is an Integration with Cachet: https://github.com/LKDevelopment/laravel-uptime-monitor-cachet-integration
