### ISSUE TITLE
Documentation for Installation should start from scratch

### ISSUE THREAD

**Issue by c33s** [spatie/laravel-uptime-monitor#54]
currently the [documentation][1] assumes that i (i think) have already installed laravel which i assume includes `artisan`

running `composer require spatie/laravel-uptime-monitor` of course leads only to:
```
 0 drwxr-xr-x 1 username groupname     0 Dec  3 04:40 .
 0 drwxr-xr-x 1 username groupname     0 Dec  3 04:24 ..
 1 -rw-r--r-- 1 username groupname    75 Dec  3 04:24 composer.json
44 -rw-r--r-- 1 username groupname 41651 Dec  3 04:24 composer.lock
 4 drwxr-xr-x 1 username groupname     0 Dec  3 04:24 vendor
```
never having used or heared from `artisan` before i assume it is a component of laravel
```
php artisan vendor:publish --provider="Spatie\UptimeMonitor\UptimeMonitorServiceProvider"
```
of course it is not that difficult to read the introduction of laravel and then return to the uptime monitors manual and continue there.

having a full documentation how to get the full app up and running would be awesome for people like me, who just want to have a selfhosted uptime monitoring.

[1]: https://docs.spatie.be/laravel-uptime-monitor/v1/installation-and-setup

**Comment by freekmurze** [comment]
Hi,

yeah you're right I assume that a reader of the documentation already knows that it's a Laravel package and most be installed into a existing Laravel app.

Though it is recommended that you do have some Laravel knowledge to run this package (in case you want to troubleshoot stuff), I'll add a page to the documentation soon that describes the install process from scratch.

**Comment by c33s** [comment]
would it be ok to reopen this ticket and close it as soon as the documentation is done? so i would get an email when the doc is done and i don't have to revisit the doc page and look if something new is there

**Comment by freekmurze** [comment]
Ok!

**Comment by freekmurze** [comment]
Hi,

I've decided against adding a separate page with dedicated instructions from scratch. Instead, I've changed various sentences throughout the docs to make it more clear that this is a package that should be installed into an existing Laravel application. I've added links to the official Laravel documentation and Artisan task runner.

If you were to write a blogpost on how you, as someone that is not too familiar with Laravel,  set up the package, I'd be more that happy to put a link to that post in our docs.

**Comment by c33s** [comment]
i think your decision is wrong. why put something on an external blogpost which is essential for using your software? the packages looks really awesome but you keep the essential docs out of the core docs.

maybe such decisions are the reason for some software beeing really successful, like for example wordpress, much much lower code quality but very easy to install, easy install docs, 

looking at your software, don't think about it as a plugin, think about it as a standalone app which is a solution for a problem a user wants to solve. 

in this case its just uptime monitoring, solved by for example:

- https://github.com/spatie/laravel-uptime-monitor
- http://uptimerobot.com/
- https://github.com/fzaninotto/uptime 

in many cases uptimerobot/any cloud solution will win, because it simply solves the problem, but as a 	opponent of cloud solutions i would be happy to see smaller apps win over the common (cloud)solutions.

user don't care if its laravel, symfony, drupal behind or if its written in js, in go or php. they see a cool promotion http://www.phpweekly.com/ and quickly want to give it a testdrive but they don't want to learn a new framework .

 don't get me wrong, i am sure is just a matter of a few minutes to get this app up and running, comming from symfony, i am sure i can handle laravel but i think it is important to provide working solutions.

so my last attempt to persuade you to add a full install doc and maybe even provide a full working edition as zip/phar which can be used out of the box. just a drop in solution.

but i will respect your decision. 

thank you for your effort you put in this awesome looking plugin.

**Comment by freekmurze** [comment]
I've quickly made this standalone version: https://github.com/spatie/uptime-monitor-app

Test it out. Do you think it's easy enough now for people coming from another framework?

I'll probably tag `1.0.0` in the coming week. If you have any remarks, open an issue at that repo.
