### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by arthurkirkosa** [spatie/laravel-uptime-monitor#59]
I keep getting `Could not reach https://deliciisanatoase.ro error: cURL error 28: Connection timed out after 17891 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)` if I manually run the command

```
curl --version
curl 7.49.1 (x86_64-apple-darwin16.0) libcurl/7.49.1 SecureTransport zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets
```

I'm on a mac.

Also, do you have a tutorial to set up crontab on mac?

**Comment by ItsRD** [comment]
I got the same thing, but via e-mail... I keep getting emails of websites which are down (same error as @arthurkirkosa)

**Comment by LKDevelopment** [comment]
we have this issue sometimes too, but we identificated that the route from the monitor host to the server changed just in this second (because of an error on provider site) so the monitoring did his job well.

**Comment by freekmurze** [comment]
Pretty certain such errors are caused by problems with connectivity on the network. If you find a bug or know a way to improve the uptime check of the package, reopen this issue.
