### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by ekka21** [spatie/laravel-uptime-monitor#71]
I run `composer require spatie/laravel-uptime-monitor` to install the app and got message below:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - spatie/laravel-uptime-monitor 1.2.1 requires illuminate/console ^5.3.28 -> satisfiable by illuminate/console[5.3.x-dev, 5.4.x-dev, 5.5.x-dev] but these conflict with your requirements or minimum-stability.
    - spatie/laravel-uptime-monitor 1.2.0 requires illuminate/console ^5.3.28 -> satisfiable by illuminate/console[5.3.x-dev, 5.4.x-dev, 5.5.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for spatie/laravel-uptime-monitor ^1.2 -> satisfiable by spatie/laravel-uptime-monitor[1.2.0, 1.2.1].

Installation failed, reverting ./composer.json to its original content.
```

**Comment by freekmurze** [comment]
Are you installing this in a L5.3 app? If so, could you please post the content of your `composer.json`?

**Comment by ekka21** [comment]
I have to apologize. I thought `composer require spatie/laravel-uptime-monitor` will install the whole thing for me(I should have read the doc better). :)

Thank you for speedy response btw!

**Comment by freekmurze** [comment]
No problem. Have fun using the package.

If you do want a quick install (without having to integrate it yourself in a Laravel app), take a look at this repo: https://github.com/spatie/uptime-monitor-app
