### ISSUE TITLE
migration is re-created everytime vendors are published

### ISSUE THREAD

**Issue by vesper8** [spatie/laravel-uptime-monitor#73]
as a result of this code which checks for CreateSitesTable instead of CreateMonitorsTable, a new migration is published every time which quickly causes duplicate migrations

```
        if (! class_exists('CreateSitesTable')) {
            $timestamp = date('Y_m_d_His', time());

            $this->publishes([
                __DIR__.'/../database/migrations/create_monitors_table.php.stub' => database_path('migrations/'.$timestamp.'_create_monitors_table.php'),
            ], 'migrations');
        }
```

I think this is just due to a typo. Your other projects implement the same logic but without this problem.

**Comment by freekmurze** [comment]
Hi, thanks for notifying me.

I've just tagged a new release `1.2.3` where this problem has been fixed.
