### ISSUE TITLE
getting a down message on an available URL

### ISSUE THREAD

**Issue by dakira** [spatie/laravel-uptime-monitor#81]
Hey. I'm wondering on how to best debug where the problem is. I'm getting a 404 on https://git.yumdap.net even though it's available. All other (https) URLs on the same server return the correct promise.

What's even stranger, when I run the uptime-check on my local machine, the URL checks out okay. Any ideas?

**Comment by freekmurze** [comment]
Could you try curling that domain on your server?

**Comment by dakira** [comment]
@freekmurze sry, forgot to mention. Curl and wget both work without problems from the same server (and user). Seems to be guzzle specific.

**Comment by freekmurze** [comment]
Your server seems to return `404` on `head` requests.
![screen shot 2017-02-07 at 19 45 42](https://cloud.githubusercontent.com/assets/483853/22706037/14ec3300-ed6e-11e6-874f-c8d16e6cadbb.jpg)

You have two options:
- let your server return a regular response code for head request
- change the request type the uptime monitor uses by modifying the `uptime_check_method` of the monitor in the database.

**Comment by dakira** [comment]
@freekmurze that's odd. I guess I'll have to submit a pull request to Gogs. Thanks for the help!
