### ISSUE TITLE
"location" missing in mails

### ISSUE THREAD

**Issue by kraftner** [spatie/laravel-uptime-monitor#84]
When notifications are sent as emails they do not include the "location".

The Slack notifications have it here:
https://github.com/spatie/laravel-uptime-monitor/blob/e8e1b62eba0abb0246cc38ec4db780b8d0fd4f58/src/Notifications/Notifications/UptimeCheckFailed.php#L47

But nothing here:
https://github.com/spatie/laravel-uptime-monitor/blob/e8e1b62eba0abb0246cc38ec4db780b8d0fd4f58/src/Notifications/Notifications/UptimeCheckFailed.php#L24-L36

**Comment by freekmurze** [comment]
Fix has been tagging. Run `composer update` to pull it in.
