### ISSUE TITLE
Using Model in API Controller

### ISSUE THREAD

**Issue by rustymulvaney** [spatie/laravel-uptime-monitor#86]
I have an API controller that I'm trying to return the Spatie\UptimeMonitor\Models\Monitor model.  All of the model fields are returned except for the "url" field which is sent as an empty object.  I am using Vue to grab the API endpoint for display.  When I use the same logic in a regular blade view, it works.

Any help would be greatly appreciated!

**Comment by ashokgelal** [comment]
I stumbled upon the same problem. What I ended up doing was extending `Monitor` class and adding a `raw_url` attribute. Something like this: https://gist.github.com/ashokgelal/fc57f175ed7e128c8bd884641dc96e03

**Comment by rustymulvaney** [comment]
@ashokgelal Worked like a charm, thank you!
