### ISSUE TITLE
Getting 405 response when curl shows 200

### ISSUE THREAD

**Issue by swilla** [spatie/laravel-uptime-monitor#88]
When I setup a monitoring with query strings, I'm getting this error:
```
Could not reach http://[ip-address]/path/to/file?market=NYC error: `Client error: `HEAD http://[ip-address]/path/to/file?market=NYC` resulted in a `405 Method Not Allowed` response:
```

If I use curl to reference that URL directly it gives a proper response and payload:
```
status@status:~$ curl http://[ip-address]/path/to/file?market=NYC -i
HTTP/1.1 200 OK
Date: Mon, 13 Mar 2017 13:26:39 GMT
Content-Type: application/json;charset=UTF-8
Connection: close
Transfer-Encoding: chunked
```

**Comment by freekmurze** [comment]
does it fail when you let curl perform a `head` request? 

Change `-i` to `-I` in your command.

If that fails as well, you could:
- let your server accept `head` requests
- or let the package send out `get` requests. You can change the request method in the `monitors` table.
