### ISSUE TITLE
Command to Send a Test Slack Message or Email

### ISSUE THREAD

**Issue by christopher-wilson** [spatie/laravel-uptime-monitor#89]
I think it would be a useful feature to have a command that will send a test slack message or email, something like `php artisan monitor:test --slack`.

I think of this because I've installed it, and it works but doesn't send anything to the webhook and there are no errors. A test command would help with troubleshooting such issues for the users.

**Comment by freekmurze** [comment]
A bit reluctant to add this becausz you could easily test this by jist using Slack on the UptimeCheckSucceeded event
