### ISSUE TITLE
Uptime not working for sites with SSL error

### ISSUE THREAD

**Issue by sumityadav** [spatie/laravel-uptime-monitor#90]
When the package detects invalid certificate, it excludes the website from Uptime monitoring too?

I think if the system finds invalid certificate, that doesn't mean that the website is down. Thoughts?

I have logged related issue at https://github.com/spatie/ssl-certificate/issues/17 repository.

**Comment by sebastiandedeyne** [comment]
What do you mean with excludes the website from monitoring?

**Comment by sumityadav** [comment]
I noticed that when the SSL monitor fails, it would not check the website uptime.

**Comment by sebastiandedeyne** [comment]
That's odd, could you share your config and host setup? Are the check commands scheduled exactly like the installation guide?

**Comment by sumityadav** [comment]
I installed the package again on fresh installation of Laravel.

Here's what is in database:
![2017-04-29_1021](https://cloud.githubusercontent.com/assets/169143/25552997/ae301824-2cc5-11e7-9c5c-35ddb7f747e3.png)

This is the sequence of commands that I ran:
![2017-04-29_1012](https://cloud.githubusercontent.com/assets/169143/25552966/0e0ecff2-2cc5-11e7-9121-61c457500df4.png)

**Comment by freekmurze** [comment]
Behind the screens the package will still check uptime for the monitor that has a failing certificate check. 

It's not being displayed in the `Healthy monitors` list because that failing certificate check makes it unhealthy.

**Comment by sumityadav** [comment]
Can we show it as Healthy and in the Certificate Check column instead of a check mark add a cross?

**Comment by freekmurze** [comment]
I prefer that when a site has a problem it isn't listed as a healty site. If you want this behaviour you could create your own list command that does this.
